## Imports

In [126]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", None)

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

# PUT GITHUB ROOT PATH HERE
root_dir = "/Users/albert/Library/CloudStorage/OneDrive-andrew.cmu.edu/Documents/CMU 26-27/Undergraduate Research/Victimization/Code/capstone_victimization"
dir = root_dir + "/Data and Resources"
os.chdir(dir)
data = pd.read_csv(os.path.join(dir, "final_data.csv"))
print(data.shape)
print(data.columns)

(8984, 26)
Index(['respondent_id', 'timely_college', 'violent_victimization_18_24',
       'earliest_arrest_before_18', 'total_number_of_incarcerations',
       'r_threatened_to_be_hurt_at_school', 'r_in_a_fight_at_school',
       'days_r_absent_from_school', 'teachers_good',
       'discipline_is_fair_agree_disagree', 'percent_of_peers_who_smoke',
       'percent_of_peers_who_get_drunk_1_times_a_month',
       'percent_of_peers_belong_to_a_gang',
       'percent_of_peers_who_have_had_sex', 'bullying_victim_before_age_12',
       'r_victim_of_bullying_12_18_years', 'sex',
       'r_ever_live_through_hard_times', 'household_net_worth',
       'household_size', 'biological_father_education',
       'biological_mother_education', 'race_ethnicity',
       'asvab_math_verbal_score_percent', 'mother_serve_prison_sentence',
       'father_serve_prison_sentence'],
      dtype='str')

In [127]:
treatment = "timely_college"
outcome = "violent_victimization_18_24"

covariates = [
    col for col in data.columns
    if col not in ["respondent_id", treatment, outcome]
]

X = data[covariates].copy()
Z = data[treatment].copy()
Y = data[outcome].copy()

In [128]:
print(Z.value_counts(dropna=False))
print(Y.value_counts(dropna=False))
for col in covariates:
    print(f"{col}: {X[col].value_counts(dropna=False)}")

timely_college
0.0    4688
1.0    4158
NaN     138
Name: count, dtype: int64
violent_victimization_18_24
0.0    7952
1.0     520
NaN     512
Name: count, dtype: int64
earliest_arrest_before_18: earliest_arrest_before_18
0    7408
1    1576
Name: count, dtype: int64
total_number_of_incarcerations: total_number_of_incarcerations
 0     7972
 1      533
 2      219
 3      105
 4       56
-3       36
 5       33
 6       15
 7        7
 8        6
 11       1
 9        1
Name: count, dtype: int64
r_threatened_to_be_hurt_at_school: r_threatened_to_be_hurt_at_school
 0     7019
 1      767
 2      415
 3      180
 5      122
-4      105
 4       83
 10      75
 20      32
 6       31
 15      24
 7       20
 8       17
 30      17
 12      14
 99      12
 50      10
-2        9
 25       7
 9        5
 17       3
 90       2
 45       2
 40       2
 16       2
 80       1
 11       1
 98       1
 13       1
 33       1
-1        1
 70       1
 19       1
 35       1
Name: count, dtype: int64
r_in_a_fight_at_school: r_in_a_fight_at_school
 0     7310
 1      897
 2      334
 3      134
-4      105
 4       63
 5       43
 6       22
 10      21
 7       14
 20       7
-2        7
 12       5
 15       4
 50       3
 25       3
 8        3
 13       2
 14       1
 22       1
 30       1
 16       1
 40       1
 11       1
 18       1
Name: count, dtype: int64
days_r_absent_from_school: days_r_absent_from_school
0     1681
2     1239
3     1094
1      959
5      831
      ...
47       1
99       1
48       1
34       1
56       1
Name: count, Length: 63, dtype: int64
teachers_good: teachers_good
 2    6192
 1    1573
 3     964
 4     236
-4      14
-2       3
-1       2
Name: count, dtype: int64
discipline_is_fair_agree_disagree: discipline_is_fair_agree_disagree
 2    4932
 3    1949
 1    1469
 4     593
-2      24
-4      14
-1       3
Name: count, dtype: int64
percent_of_peers_who_smoke: percent_of_peers_who_smoke
 1    2322
 3    2172
 2    1966
 4    1657
 5     754
-2     104
-4       6
-1       2
-3       1
Name: count, dtype: int64
percent_of_peers_who_get_drunk_1_times_a_month: percent_of_peers_who_get_drunk_1_times_a_month
 1    3846
 2    1890
 3    1571
 4    1003
 5     489
-2     177
-4       6
-3       1
-1       1
Name: count, dtype: int64
percent_of_peers_belong_to_a_gang: percent_of_peers_belong_to_a_gang
 1    5690
 2    1829
 3     698
 4     364
 5     231
-2     163
-4       6
-1       2
-3       1
Name: count, dtype: int64
percent_of_peers_who_have_had_sex: percent_of_peers_who_have_had_sex
-4    4837
 3    1158
 2     855
 4     714
 1     696
 5     542
-2     176
-1       5
-3       1
Name: count, dtype: int64
bullying_victim_before_age_12: bullying_victim_before_age_12
 0    7120
 1    1713
-3     126
-1      13
-2      11
-4       1
Name: count, dtype: int64
r_victim_of_bullying_12_18_years: r_victim_of_bullying_12_18_years
0.0    6060
NaN    2025
1.0     899
Name: count, dtype: int64
sex: sex
1    4599
2    4385
Name: count, dtype: int64
r_ever_live_through_hard_times: r_ever_live_through_hard_times
 0    7440
-4    1084
 1     435
-2      18
-1       7
Name: count, dtype: int64
household_net_worth: household_net_worth
-3         1314
-4         1051
 500        202
 600000     178
 3750       138
           ...
 556000       1
 75001        1
 27406        1
 217501       1
 236000       1
Name: count, Length: 2513, dtype: int64
household_size: household_size
4     2857
5     2163
3     1605
6     1052
2      480
7      428
8      220
9       79
10      57
11      27
13       7
12       3
15       2
16       2
14       1
1        1
Name: count, dtype: int64
biological_father_education: biological_father_education
 12    2728
-3     1188
 16     840
 14     736
-4      668
 11     396
 13     381
 10     329
 18     270
 9      240
 6      188
 15     176
 8      169
 20     162
 17     113
 7       92
 19      85
 5       68
 3       68
 4       59
 2       19
 95       8
 1        1
Name: count, dtype: int64
biological_mother_education: biological_mother_education
 12    3038
 14    1002
 16     908
 13     642
 11     562
-3      523
 10     428
 9      273
 15     248
 18     227
 6      222
 8      205
-4      165
 17     157
 20      77
 7       69
 5       57
 3       54
 4       52
 19      34
 2       29
 95       6
 1        6
Name: count, dtype: int64
race_ethnicity: race_ethnicity
White       4413
Black       2334
Hispanic    1899
Other        182
Asian        156
Name: count, dtype: int64
asvab_math_verbal_score_percent: asvab_math_verbal_score_percent
-0.004      1891
 100.000      20
 0.000        20
 40.241        3
 44.725        3
            ...
 12.716        1
 27.785        1
 96.478        1
 61.580        1
 71.549        1
Name: count, Length: 6821, dtype: int64
mother_serve_prison_sentence: mother_serve_prison_sentence
 0    6976
-5    1844
 1      94
-2      63
-1       7
Name: count, dtype: int64
father_serve_prison_sentence: father_serve_prison_sentence
 0    6079
-5    1844
 1     430
-4     335
-2     287
-1       9
Name: count, dtype: int64

## Remove survey non-responses

In [129]:
# Replace negative values with NaN for numeric variables
numeric_cols = X.select_dtypes(include="number").columns

X[numeric_cols] = X[numeric_cols].mask(X[numeric_cols] < 0)

# Also remove invalid treatment/outcome values
Z = Z.mask(Z < 0)
Y = Y.mask(Y < 0)

In [130]:
# Propensity scores require a known treatment value
valid_treatment = Z.notna()

X = X.loc[valid_treatment].copy()
Z = Z.loc[valid_treatment].copy()
Y = Y.loc[valid_treatment].copy()

## Separate numeric vs categorical

In [131]:
print(X.columns)

Index(['earliest_arrest_before_18', 'total_number_of_incarcerations',
       'r_threatened_to_be_hurt_at_school', 'r_in_a_fight_at_school',
       'days_r_absent_from_school', 'teachers_good',
       'discipline_is_fair_agree_disagree', 'percent_of_peers_who_smoke',
       'percent_of_peers_who_get_drunk_1_times_a_month',
       'percent_of_peers_belong_to_a_gang',
       'percent_of_peers_who_have_had_sex', 'bullying_victim_before_age_12',
       'r_victim_of_bullying_12_18_years', 'sex',
       'r_ever_live_through_hard_times', 'household_net_worth',
       'household_size', 'biological_father_education',
       'biological_mother_education', 'race_ethnicity',
       'asvab_math_verbal_score_percent', 'mother_serve_prison_sentence',
       'father_serve_prison_sentence'],
      dtype='str')

In [132]:
numeric_features = [
    "total_number_of_incarcerations",
    "days_r_absent_from_school",
    "r_threatened_to_be_hurt_at_school",
    "r_in_a_fight_at_school",
    "household_net_worth",
    "household_size",
    "asvab_math_verbal_score_percent"
]
categorical_features = [
    "teachers_good",
    "discipline_is_fair_agree_disagree",
    "percent_of_peers_who_smoke",
    "percent_of_peers_who_get_drunk_1_times_a_month",
    "percent_of_peers_belong_to_a_gang",
    "percent_of_peers_who_have_had_sex",
    "bullying_victim_before_age_12",
    "r_victim_of_bullying_12_18_years",
    "earliest_arrest_before_18",
    "sex",
    "r_ever_live_through_hard_times",
    "biological_father_education", # 95 = ungraded
    "biological_mother_education", # 95 = ungraded
    "race_ethnicity",
    "mother_serve_prison_sentence",
    "father_serve_prison_sentence"
]

In [133]:
for f in numeric_features:
    if f not in X.columns:
        print(f"Warning: {f} not found in X columns")
    else:
        print(f)

total_number_of_incarcerations
days_r_absent_from_school
r_threatened_to_be_hurt_at_school
r_in_a_fight_at_school
household_net_worth
household_size
asvab_math_verbal_score_percent

In [134]:
for f in categorical_features:
    if f not in X.columns:
        print(f"Warning: {f} not found in X columns")
    else:
        print(f)

teachers_good
discipline_is_fair_agree_disagree
percent_of_peers_who_smoke
percent_of_peers_who_get_drunk_1_times_a_month
percent_of_peers_belong_to_a_gang
percent_of_peers_who_have_had_sex
bullying_victim_before_age_12
r_victim_of_bullying_12_18_years
earliest_arrest_before_18
sex
r_ever_live_through_hard_times
biological_father_education
biological_mother_education
race_ethnicity
mother_serve_prison_sentence
father_serve_prison_sentence

## Preprocess for logistic regression
Impute numerical with median, and impute categorical with mode.
Also one-hot encode categoricals

In [135]:
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_transformer, numeric_features),
    ("categorical", categorical_transformer, categorical_features)
])

## Create propensity score model

In [136]:
ps_model = Pipeline([
    ("preprocessor", preprocessor),
    ("logistic", LogisticRegression(max_iter=1000))
])

## Estimate propensity scores

In [137]:
ps_model.fit(X, Z)

propensity_scores = ps_model.predict_proba(X)[:, 1]

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [138]:
data_ps = data.loc[valid_treatment].copy()

data_ps["propensity_score"] = propensity_scores

data_ps[[
    treatment,
    "propensity_score"
]].head()

   timely_college  propensity_score
0             0.0          0.609911
1             1.0          0.663704
2             0.0          0.374415
3             1.0          0.404602
4             0.0          0.434257

## Propensity Score Distributions

In [139]:
import plotly.express as px

fig = px.histogram(
    data_ps,
    x="propensity_score",
    color=treatment,
    nbins=100,
    barmode="overlay",
    opacity=0.6,
    title="Propensity Score Distribution by Treatment Group",
)

fig.update_layout(
    xaxis_title="Propensity Score",
    yaxis_title="Count",
    width=800
)

fig.show()

## LR Coefficients

In [140]:
feature_names = ps_model.named_steps["preprocessor"].get_feature_names_out()

# 3. Extract the coefficients from the logistic regression step
coefficients = ps_model.named_steps["logistic"].coef_[0]

# 4. Create a clean DataFrame matching names to coefficients
coef_summary = pd.DataFrame({
    'Feature': feature_names,
    'Coefficient': coefficients
})

coef_summary.sort_values(by='Coefficient', ascending=False, inplace=True)
coef_summary

                                          Feature  Coefficient
81  categorical__biological_mother_education_16.0     0.302566
39       categorical__earliest_arrest_before_18_0     0.289158
60  categorical__biological_father_education_16.0     0.193504
58  categorical__biological_father_education_14.0     0.121787
7                  categorical__teachers_good_1.0     0.119267
..                                            ...          ...
56  categorical__biological_father_education_12.0    -0.211068
41                             categorical__sex_1    -0.216433
9                  categorical__teachers_good_3.0    -0.249980
40       categorical__earliest_arrest_before_18_1    -0.456009
0         numeric__total_number_of_incarcerations    -0.573029

[96 rows x 2 columns]